/* tslint:disable */
/* eslint-disable */
/* auto-generated by napi-rs - do not hand-edit */

// ─── Core API Types (hand-written, mirroring index.js exports) ────────

/**
 * Options for launching a browser instance.
 * Mirrors the options accepted by `launch()` in index.js.
 */
export interface LaunchOptions {
  /** Whether to run the browser in headless mode (default: false) */
  headless?: boolean;
  /** Additional command-line arguments passed to the browser */
  args?: string[];
  [key: string]: unknown;
}

/**
 * A browser instance. Created via {@link launch}.
 */
export interface Browser {
  /** Create a new browser context (incognito session). */
  newContext(): Promise<BrowserContext>;
  /** Close the browser and all its contexts. */
  close(): Promise<void>;
}

/**
 * A locator for querying and interacting with elements on a page.
 */
export interface Locator {
  /** Click the element */
  click(): Promise<void>;
  /** Fill an input with text */
  fill(value: string): Promise<void>;
  /** Get the text content of the element */
  textContent(): Promise<string | null>;
  /** Get the inner text of the element */
  innerText(): Promise<string>;
  /** Get the inner HTML of the element */
  innerHTML(): Promise<string>;
  /** Get an attribute value by name */
  getAttribute(name: string): Promise<string | null>;
  /** Check if the element is disabled */
  isDisabled(): Promise<boolean>;
  /** Check if the element is enabled */
  isEnabled(): Promise<boolean>;
  /** Check if the element is visible */
  isVisible(): Promise<boolean>;
  /** Get the count of matching elements */
  count(): Promise<number>;
  /** Evaluate JavaScript in the element's context */
  evaluate(js: string): Promise<any>;
  /** Focus the element */
  focus(): Promise<void>;
  /** Blur the element */
  blur(): Promise<void>;
  /** Hover over the element */
  hover(): Promise<void>;
  /** Scroll the element into view */
  scrollIntoView(): Promise<void>;
  /** Check a checkbox or radio */
  check(): Promise<void>;
  /** Uncheck a checkbox */
  uncheck(): Promise<void>;
  /** Select an option by value */
  select(value: string): Promise<void>;
  /** Double-click the element */
  dblclick(): Promise<void>;
  /** Right-click the element */
  rightClick(): Promise<void>;
}

/**
 * Launch a browser instance.
 * @param options Optional launch configuration.
 */
export function launch(options?: LaunchOptions): Promise<Browser>;

/**
 * Return the version string of the native binary.
 */
export function version(): string;

// ─── Video Recording Types ────────────────────────────────────────────

/**
 * Check if the video recording feature is available in this build.
 * Returns `true` when the binary was compiled with `--features video`.
 */
export function videoIsAvailable(): boolean;

/**
 * Options for configuring video recording on a page.
 * Passed as a JSON string to `VideoRecorderHandle.start()` or
 * `ContextVideoHandle.setDefaults()`.
 */
export interface VideoConfig {
  /** Recording FPS (default: 10) */
  fps?: number;
  /** JPEG quality 1-100 (default: 80) */
  quality?: number;
  /** Max frame width (default: 800) */
  maxWidth?: number;
  /** Max frame height (default: 600) */
  maxHeight?: number;
  /** Video bitrate in bits per second (default: 500_000) */
  bitrate?: number;
  /** Codec: "vp8", "vp9", "h264", "h265" (default: "vp8") */
  codec?: string;
  /** Output directory for video files */
  outputDir?: string;
  /** Retention policy: "on-failure", "always", "never" (default: "on-failure") */
  retention?: string;
}

/**
 * Handle returned by `page.video()` for controlling video recording
 * on a single page with a fluent API.
 */
export class VideoRecorderHandle {
  /**
   * Start video recording with optional config.
   * @param configJson Optional JSON-serialised VideoConfig
   */
  start(configJson?: string): Promise<void>;
  /**
   * Stop video recording and return the video file path,
   * or `null` if no recording was active.
   * @param testPassed When true/false, applies retention policy
   *   (e.g. `OnFailure` deletes the file on pass). Omit to keep.
   */
  stop(testPassed?: boolean): Promise<string | null>;
  /**
   * Return the video file path after recording completes, or `null` before.
   */
  path(): string | null;
}

/**
 * Handle returned by `context.video()` for configuring context-level
 * video recording defaults.
 */
export class ContextVideoHandle {
  /**
   * Set default video recording config for this context as a JSON string.
   * Pages created from this context may use these defaults.
   */
  setDefaults(configJson: string): void;
  /**
   * Get the current default video recording config for this context,
   * or `null` if none set.
   */
  getDefaults(): string | null;
  /**
   * Clear the default video recording config for this context.
   */
  clearDefaults(): void;
}

// ─── Augment existing types ───────────────────────────────────────────

export interface Page {
  /** Navigate to a URL */
  goto(url: string): Promise<void>;
  /** Create a locator for the given selector */
  locator(selector: string): Locator;
  /** Close the page */
  close(): Promise<void>;
  /** Get the full page HTML content */
  content(): Promise<string>;
  /** Get the page title */
  title(): Promise<string>;
  /** Get the current page URL */
  url(): string;
  /** Execute JavaScript in the page context */
  evaluate(js: string): Promise<any>;
  /**
   * Return a `VideoRecorderHandle` for this page.
   * Requires the `video` feature.
   */
  video(): VideoRecorderHandle;
  /**
   * Start video recording for this page.
   * @deprecated Use `page.video().start()` instead.
   */
  startVideoRecording(configJson?: string): Promise<void>;
  /**
   * Stop video recording for this page.
   * @param testPassed When true/false, applies retention policy.
   * @deprecated Use `page.video().stop(testPassed)` instead.
   */
  stopVideoRecording(testPassed?: boolean): Promise<string | null>;
}

export interface BrowserContext {
  /** Create a new page (tab) in this context */
  newPage(): Promise<Page>;
  /**
   * Return a `ContextVideoHandle` for configuring context-level
   * video recording options. Requires the `video` feature.
   */
  video(): ContextVideoHandle;
}
